
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principal.java
 *
 * Created on 01/04/2011, 06:04:05 PM
 */
/**
 *
 * @author silvia
 */
public class Principal extends javax.swing.JFrame {

    /** Creates new form Principal */
    public Principal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        pregunta1 = new javax.swing.JCheckBox();
        Pregunta14 = new javax.swing.JCheckBox();
        Pregunta3 = new javax.swing.JCheckBox();
        Pregunta15 = new javax.swing.JCheckBox();
        Pregunta4 = new javax.swing.JCheckBox();
        Pregunta13 = new javax.swing.JCheckBox();
        Pregunta6 = new javax.swing.JCheckBox();
        Pregunta9 = new javax.swing.JCheckBox();
        Pregunta11 = new javax.swing.JCheckBox();
        Pregunta2 = new javax.swing.JCheckBox();
        Pregunta12 = new javax.swing.JCheckBox();
        Pregunta5 = new javax.swing.JCheckBox();
        Pregunta10 = new javax.swing.JCheckBox();
        Pregunta7 = new javax.swing.JCheckBox();
        Pregunta8 = new javax.swing.JCheckBox();
        Pregunta17 = new javax.swing.JCheckBox();
        Pregunta18 = new javax.swing.JCheckBox();
        Pregunta16 = new javax.swing.JCheckBox();
        Pregunta19 = new javax.swing.JCheckBox();
        Pregunta20 = new javax.swing.JCheckBox();
        btnDiagnosticar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiManual = new javax.swing.JMenuItem();
        jmiDesarrollar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA EXPERTO");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SINTOMAS GENERALES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.black));
        jPanel2.setForeground(new java.awt.Color(204, 255, 255));

        pregunta1.setText("Dolor de cabeza Recurrente");
        pregunta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pregunta1ActionPerformed(evt);
            }
        });

        Pregunta14.setText("Náuseas o vómito.");

        Pregunta3.setText("Escucha pequeños ruidos.");
        Pregunta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pregunta3ActionPerformed(evt);
            }
        });

        Pregunta15.setText("Observa pequeñas luces como destellos.");

        Pregunta4.setText("Falta de apetito.");

        Pregunta13.setText("Visión es borrosa.");

        Pregunta6.setText("Disminución de la concentración.");

        Pregunta9.setText("Nariz congestionada.");

        Pregunta11.setText("Sensación de hambre");

        Pregunta2.setText("Pierde temporalmente la visión");

        Pregunta12.setText("Se le adormecen las manos, recorre por el brazo hasta llegar a la boca");

        Pregunta5.setText("Problemas al hablar");

        Pregunta10.setText("Su sudoración es excesiva.");

        Pregunta7.setText("Trasnoches muy seguidas");

        Pregunta8.setText("Pasas mucho tiempo en el sol.");

        Pregunta17.setText("Sensación de frío y calor.");

        Pregunta18.setText("Gripe.");

        Pregunta16.setText("Dolores de la garganta.");
        Pregunta16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pregunta16ActionPerformed(evt);
            }
        });

        Pregunta19.setText("Infecciones al oido.");
        Pregunta19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pregunta19ActionPerformed(evt);
            }
        });

        Pregunta20.setText("Antes del dolor de cabeza tiene destellos de luces.");
        Pregunta20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pregunta20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pregunta1)
                    .addComponent(Pregunta3)
                    .addComponent(Pregunta2)
                    .addComponent(Pregunta4)
                    .addComponent(Pregunta5)
                    .addComponent(Pregunta6)
                    .addComponent(Pregunta7)
                    .addComponent(Pregunta8)
                    .addComponent(Pregunta10)
                    .addComponent(Pregunta9))
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pregunta20)
                    .addComponent(Pregunta19)
                    .addComponent(Pregunta16)
                    .addComponent(Pregunta18)
                    .addComponent(Pregunta17)
                    .addComponent(Pregunta14)
                    .addComponent(Pregunta15)
                    .addComponent(Pregunta13)
                    .addComponent(Pregunta11)
                    .addComponent(Pregunta12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pregunta1)
                    .addComponent(Pregunta11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pregunta12)
                    .addComponent(Pregunta2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pregunta3)
                    .addComponent(Pregunta13))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pregunta4)
                    .addComponent(Pregunta14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pregunta5)
                    .addComponent(Pregunta15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pregunta6)
                    .addComponent(Pregunta16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pregunta7)
                    .addComponent(Pregunta17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pregunta8)
                    .addComponent(Pregunta18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pregunta19)
                    .addComponent(Pregunta9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pregunta10)
                    .addComponent(Pregunta20))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDiagnosticar.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
        btnDiagnosticar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Head-physician.png"))); // NOI18N
        btnDiagnosticar.setText("DIAGNOSTICAR");
        btnDiagnosticar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagnosticarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bio-hazard.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("SELECCIONE LOS SINTOMAS QUE USTED POSEA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(771, 771, 771)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 5, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addComponent(btnDiagnosticar)
                .addGap(107, 107, 107)
                .addComponent(btnCancelar)
                .addGap(175, 175, 175))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(422, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnDiagnosticar))
                .addGap(65, 65, 65)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DIAGNÓSTICO Y TRATAMIENTO", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 153, 0));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\silvia\\Documents\\NetBeansProjects\\Experto\\src\\Imagenes\\salsa de tomate contra la migraña.jpg")); // NOI18N
        jButton1.setToolTipText("");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setDefaultCapable(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setOpaque(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.setRolloverEnabled(false);
        jButton1.setVerifyInputWhenFocusTarget(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        jMenuItem1.setText("SALIR");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jmiManual.setText("MANUAL");
        jMenu2.add(jmiManual);

        jmiDesarrollar.setText("DESARROLLADOR");
        jMenu2.add(jmiDesarrollar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pregunta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pregunta1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_pregunta1ActionPerformed

    private void Pregunta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pregunta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pregunta3ActionPerformed

    private void Pregunta16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pregunta16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pregunta16ActionPerformed

    private void Pregunta19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pregunta19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pregunta19ActionPerformed

    private void btnDiagnosticarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagnosticarActionPerformed
        // TODO add your handling code here:
        if (compruebaSeleccion() == false) {
            JOptionPane.showMessageDialog(this, "POR FAVOR SELECCIONE POR LO MENOS UN SINTOMA ");
        } else if (pregunta1.isSelected() && Pregunta15.isSelected() && Pregunta13.isSelected() == true) {
            if (Pregunta14.isSelected() || Pregunta3.isSelected() || Pregunta4.isSelected()
                    || Pregunta6.isSelected() || Pregunta9.isSelected() || Pregunta11.isSelected()
                    || Pregunta10.isSelected() || Pregunta17.isSelected() || Pregunta18.isSelected()
                    || Pregunta19.isSelected() || Pregunta7.isSelected() || Pregunta16.isSelected() == true) {
            }
            JOptionPane.showConfirmDialog(this, "USTED TIENE MIGRAÑA SIN AURA");
            jTextArea1.setText("EL TRATAMIENTO A SEGUIR ES........");

        } else if (Pregunta20.isSelected() && pregunta1.isSelected() && Pregunta12.isSelected() == true) {
            if (Pregunta2.isSelected() || Pregunta3.isSelected() || Pregunta4.isSelected()
                    || Pregunta5.isSelected() || Pregunta6.isSelected() || Pregunta7.isSelected()
                    || Pregunta8.isSelected() || Pregunta9.isSelected() || Pregunta10.isSelected()
                    || Pregunta11.isSelected() || Pregunta13.isSelected() || Pregunta14.isSelected()
                    || Pregunta15.isSelected() || Pregunta16.isSelected() || Pregunta17.isSelected()
                    || Pregunta18.isSelected() || Pregunta19.isSelected() || Pregunta20.isSelected()
                    == true) {
            }
            JOptionPane.showConfirmDialog(this, "USTED TIENE MIGRAÑA CON AURA");
            jTextArea1.setText("EL TRATAMIENTO A SEGUIR ES.III.......");

        } else if (pregunta1.isSelected() == true) {
            if (Pregunta18.isSelected() || Pregunta19.isSelected()
                    || Pregunta7.isSelected() || Pregunta8.isSelected()
                    || Pregunta16.isSelected() || Pregunta19.isSelected()
                    == true) {
                JOptionPane.showConfirmDialog(this, "USTED TIENE UN DOLOR DE CABEZA NORMAL");
            } else
            JOptionPane.showConfirmDialog(this, "CONSULTE A SU MÉDICO PARA QUE DIAGNOSTIQUE SU DOLENCIA O ADICIONE OTRO SÍNTOMA");
        } else {
            JOptionPane.showConfirmDialog(this, "CONSULTE A SU MÉDICO PARA QUE DIAGNOSTIQUE SU DOLENCIA");
        }
    }//GEN-LAST:event_btnDiagnosticarActionPerformed

    private void Pregunta20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pregunta20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pregunta20ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    public boolean compruebaSeleccion() {

        Object[] componentes = jPanel2.getComponents();

        for (int i = 0; i < componentes.length; i++) {
            JCheckBox pre1 = (JCheckBox) componentes[i];
            if (pre1.isSelected() == true) {
                return true;
            }
        }
        return false;
    }

    public boolean compruebaDesSeleccion() {

        Object[] componentes = jPanel2.getComponents();

        for (int i = 0; i < componentes.length; i++) {
            JCheckBox pre1 = (JCheckBox) componentes[i];
            if (pre1.isSelected() == true) {
                return true;
            }
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Pregunta10;
    private javax.swing.JCheckBox Pregunta11;
    private javax.swing.JCheckBox Pregunta12;
    private javax.swing.JCheckBox Pregunta13;
    private javax.swing.JCheckBox Pregunta14;
    private javax.swing.JCheckBox Pregunta15;
    private javax.swing.JCheckBox Pregunta16;
    private javax.swing.JCheckBox Pregunta17;
    private javax.swing.JCheckBox Pregunta18;
    private javax.swing.JCheckBox Pregunta19;
    private javax.swing.JCheckBox Pregunta2;
    private javax.swing.JCheckBox Pregunta20;
    private javax.swing.JCheckBox Pregunta3;
    private javax.swing.JCheckBox Pregunta4;
    private javax.swing.JCheckBox Pregunta5;
    private javax.swing.JCheckBox Pregunta6;
    private javax.swing.JCheckBox Pregunta7;
    private javax.swing.JCheckBox Pregunta8;
    private javax.swing.JCheckBox Pregunta9;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDiagnosticar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenuItem jmiDesarrollar;
    private javax.swing.JMenuItem jmiManual;
    private javax.swing.JCheckBox pregunta1;
    // End of variables declaration//GEN-END:variables
}
